### ISSUE TITLE
Original Kaggle data

### ISSUE THREAD

**Issue by MoniWong** [garethjns/Kaggle-EEG#12]
Hello,garethjns
I’m an entire beginner of Kaggle- eeg competition, and I want to run your code to learn step by step. But I sadly find the eeg data has been removed from Kaggle.So I wonder if you still store the data and could send some to me?
Thank you very much.

**Comment by garethjns** [comment]
Hi MoniWong,

Apologies for the delay replying. Unfortunately, the data isn't mine and I don't have it available to share. I'd suggest contacting Levin Kuhlmann at the University of Melbourne, who may still be able to provide it. Otherwise, there are a couple of other EEG competitions which still have data on Kaggle (for example, https://www.kaggle.com/c/seizure-detection). I haven't looked at these myself but with a bit of preprocessing the data might be usable with the code here.

Cheers,
Gareth
