### ISSUE TITLE
Predict.m error

### ISSUE THREAD

**Issue by dispo3c** [garethjns/Kaggle-EEG#9]
Greetings dear. At the moment of running predict.m I get the following error:
''

>Creating basic features
Error using featuresObject.genFileListNoConcat (line 644)
To assign to or create a variable in a table, the number of rows must match the height of the table.
Error in featuresObject/getFileLists (line 265)
                        obj.genFileListNoConcat({'1','2','3'}, ...
Error in featuresObject/setFileLists (line 247)
                    getFileLists(obj);
Error in featuresObject (line 59)
            obj = setFileLists(obj, {});
Error in predict (line 77)
featuresTest = featuresObject(params, use);

''
I would be very grateful if you could help me.
Best regards.

**Comment by garethjns** [comment]
Hi dispo3c,

I suspect the problem here is that no files are being found from the test set. 

The path setting is a bit messy and I've been changing this code around for various reasons recently, so I may have introduced a bug, or the folder structure may be set up incorrectly on your computer.

I'll have a look and get back to you shortly.

Cheers,
Gareth

**Comment by garethjns** [comment]
Hi dispo3c,

I've corrected a mistake in the paths. I don't actually have the second test set as released on Kaggle anymore - but if I remember correctly the folders had "_New" in their names?

The code should now run as long as your data folder looks like this:
https://github.com/garethjns/Kaggle-EEG/blob/master/Images/folderStructure3.png

I've also updated the readme with more detailed instructions. Please let me know if you can get it to work now!

Cheers,
Gareth
